
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-namespace
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: gcr.io/PROJECT/BACKEND
          resources:
            limits:
              cpu: "150m"
              memory: "50Mi"
          volumeMounts:
          - name: image-volume
            mountPath: /shared/image
          env:
          - name: IMAGE_DIR
            value: "/shared/image"
          - name: POSTGRES
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-host
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: POSTGRES_PASSWORD
