apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-apps
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: thesamsai/ping-pong:v5
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
          env:
            - name: POSTGRES
              value: "postgres-svc/pingpong"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
